name: Test (Reusable)

# Trigger Rules:
# - only run on when triggered by another workflow

on:
  workflow_call:

env:
  EXAMPLE_SECRET: EXAMPLE_SECRET

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show Output
        run: echo "Reusable workflow called"
