name: Build

# Trigger Rules:
# - run on all pull requests

on:
  pull_request:
    branches:
      - "**"

env:
  COMMIT_SHA: ${{ github.sha }}

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Show Output
        run: echo "Runs on all pull pequests"
