name: Deployment

# Trigger Rules:
# - only run on closed pull requests to master

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Show Output
        run: echo "Deployment Workflow running - this workflow should only run when a PR is merged (closed) into the main branch"
