name: Deployment

# Trigger Rules:
# - only run on closed pull requests to master

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    name: Pubish
    runs-on: ubuntu-latest

    steps:
      - name: Show Output
        run: echo "Reqires first job to complete. Second job has now completed"
