name: Print

on:
  push:
    branches:
      - print

jobs:
  print:
    name: Dump Github Context
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}

    steps:
      - name: Print Github Context using toJson command
        run: echo "${{ toJson(github) }}"

      - name: Print Repository name
        run: echo "${{ github.event.repository.name }}"

      - name: Print Repository (user/repo)
        run: echo "${{ github.repository }}"
