name: Print

# Trigger Rules:
# - only run on closed pull requests to master

on:
  push:
    branches:
      - print

jobs:
  print:
    name: Dump Github Context
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}

    steps:
      - name: Print Github Context using toJson command
        run: echo "${{ toJson(github) }}"
