name: Test

# Trigger Rules:
# - run on all pull requests

on:
  pull_request:
    branches:
      - "**"

env:
  EXAMPLE_SECRET: EXAMPLE_SECRET

jobs:
  reusable:
    name: Test Workflow (Reusable)
    uses: "joepk90/github-actions-examples/.github/workflows/0-reusable-workflow.yaml@main"
    secrets: inherit
